services:

  dts-feature-extraction-norton670:
    container_name: dts-feature-extraction-norton670
    image: ghcr.io/malware-concept-drift-detection/dts-features-extraction:main
    environment:
      MALWARE_DIR_PATH: /usr/input_data/malware/
      SPLITTED_DATASET_PATH: /usr/input_data/splitted_dataset/
      FINAL_DATASET_DIR: /usr/app/data/
      N_PROCESSES: 64
    volumes:
      - "/home/luca/Malware-Concept-Drift-Detection/train_test_splits/splitted_dataset/Norton670_pre/dupl/time_split/:/usr/input_data/splitted_dataset/"
      - "/home/luca/MNTPOINT/SAMPLES/malpe/:/usr/input_data/malware/"
      - "./features_extraction:/usr/app/features_extraction/"
      - "./data_norton670/:/usr/app/data/"
